### PR TITLE
[hotfix] issues-382 / fix Read Timeout And issues-374 / getting information of current process infomation by top command

### PR DESCRIPTION
**Pull request by LeeKyoungIl**
change socket options. 
- when receiving large packets from the scouter server. (for example 'HOST_TOP')
   soTimeout value is small (8sec) and Read Timeout occurs.
 - soTimeout value is that check the time from the start of data send to the end.
   so neceassary to set more value. (8sec -> 15sec)
 - and I did some tuning of Socket options.

### CODE REVIEW

**Comment by LeeKyoungIl** [comment]
with issue 374 - https://github.com/scouter-project/scouter/issues/374

getting information of current process infomation by top command

**Comment by gunlee01** [comment]
Please let me know the reason why you use ```setPerformancePreferences(2, 0, 1)``` ?

**Comment by gunlee01** [comment]
We need to get CLA for ons's the first commit.
Do CLA below and comment the URL.
https://docs.google.com/forms/d/e/1FAIpQLSfio6M8TIuD8RodE3Z4zBCMABeQ8uJCAf_mr8erUQLkJOc3kg/viewform?c=0&w=1

**Comment by LeeKyoungIl** [comment]
@gunlee01 
I think, the most important thing in socket communications between the Scouter server and Web api instance. 
latency > bandwidth  > connectionTime  so I set 2, 0, 1 

method Specification.
 - setPerformancePreferences(int connectionTime, int latency, int bandwidth)

If you have any idea, you can set it differently. ^^

**Comment by gunlee01** [comment]
latency > bandwidth > connectionTime,
then 0, 2, 1 isn't it?

**Comment by LeeKyoungIl** [comment]
@gunlee01 
In API doc. 
Negative values represent a lower priority than positive values.

latency > bandwidth > connectionTime,

 - latency = 0 
 - bandwidth = 1
 - connectionTime = 2

**Comment by gunlee01** [comment]
I understand it, high value for high prioty.
If I want to mark a latency as highest prioty, 
then values to it higher than others.
I misunderstood it?

**Comment by LeeKyoungIl** [comment]
@gunlee01 
Oops. sorry.

latency < bandwidth < connectionTime,

latency = 0
bandwidth = 1
connectionTime = 2

I misrepresented the the Inequality.

**Pull request merged**
